[package]
name = "service-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { verison = "4.4.18", features = ["derive"] }
config = "0.13.4"
criterion = "0.5.1"
eyre = "0.6.11"
sqlx = { version = "0.7.3", features = [
    "runtime-tokio-native-tls",
    "any",
    "postgres",
    "chrono",
] }
telemetry-batteries = { git = "https://github.com/worldcoin/telemetry-batteries.git", commit = "c6816624415ae194da5203a5161621a9e10ad3b0" }
tokio = { version = "1.35.1", features = ["macros"] }
tracing = "0.1.40"

[[bin]]
name = "service"
path = "bin/service.rs"

[[bench]]
name = "example"
harness = false
