[package]
name = "service-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive", "env"] }
config = "0.13.4"
dotenv = "0.15.0"
criterion = "0.5.1"
eyre = "0.6.11"
sqlx = { version = "0.7.3", features = [
    "runtime-tokio-native-tls",
    "any",
    "postgres",
    "chrono",
] }
telemetry-batteries = { git = "https://github.com/worldcoin/telemetry-batteries.git", rev = "c6816624415ae194da5203a5161621a9e10ad3b0" }
tokio = { version = "1.35.1", features = ["macros"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
metrics = "0.21.1"

[[bin]]
name = "mpc-node"
path = "bin/mpc_node.rs"

[[bench]]
name = "example"
harness = false
