name: E2E Tests

on: [push, pull_request]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    # Setup Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - run: docker-compose pull

    # Cache
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    # Starting background services
    - name: Start background services
      run: docker compose up -d --build localstack coordinator participant coordinator_db participant_db

    # Running e2e tests
    - name: Run e2e tests
      run: docker compose up --build --abort-on-container-exit --exit-code-from e2e_test
      # Ensure the action fails if the e2e_test service fails
      continue-on-error: false

    # Cleanup
    - name: Cleanup
      if: always()
      run: docker compose down --volumes --remove-orphans
